package com.mycompany.bookingsystem;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class adminPage extends javax.swing.JFrame {

    /**
     * Creates new form adminPage
     */
    public adminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnUDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        btnUClear = new javax.swing.JButton();
        btnUAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUSearch = new javax.swing.JTextField();
        btnUSearch = new javax.swing.JButton();
        btnUView = new javax.swing.JButton();
        btnUEdit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRTable = new javax.swing.JTable();
        txtRSearch = new javax.swing.JTextField();
        btnRSearch = new javax.swing.JButton();
        btnRView = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        txtRGenre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnRClear = new javax.swing.JButton();
        btnRAdd = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtRShowTime = new javax.swing.JTextField();
        txtRQTY = new javax.swing.JTextField();
        txtRFilm = new javax.swing.JTextField();
        btnRDelete = new javax.swing.JButton();
        btnREdit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnMDelete = new javax.swing.JButton();
        btnMEdit = new javax.swing.JButton();
        txtMSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmbMCinema = new javax.swing.JComboBox<>();
        cmbMGenre = new javax.swing.JComboBox<>();
        txtMDate = new javax.swing.JTextField();
        cmbMStatus = new javax.swing.JComboBox<>();
        cmbMTime = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnMClear = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        cmbMScreen = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtMFilm = new javax.swing.JTextField();
        btnMSearch = new javax.swing.JButton();
        btnMView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(37, 18, 17));

        jPanel9.setBackground(new java.awt.Color(119, 10, 10));

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"admin", "ADMIN", "111"},
                {"vip", "VIP", "333"},
                {"customer", "CUSTOMER", "222"}
            },
            new String [] {
                "USERNAME", "ROLE", "PASSWORD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsersMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUsers);

        btnUDelete.setText("DELETE RECORD");
        btnUDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUDeleteActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(119, 10, 10));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 177, 164)));

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "CUSTOMER", "VIP" }));
        cmbRole.setSelectedIndex(-1);
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        btnUClear.setText("CLEAR");
        btnUClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUClearActionPerformed(evt);
            }
        });

        btnUAdd.setText("ADD RECORD");
        btnUAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUAddActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ROLE");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnUClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUAdd))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUAdd)
                    .addComponent(btnUClear)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnUSearch.setText("SEARCH");
        btnUSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSearchActionPerformed(evt);
            }
        });

        btnUView.setText("VIEW ALL");
        btnUView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUViewActionPerformed(evt);
            }
        });

        btnUEdit.setText("EDIT RECORD");
        btnUEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUEditActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SEARCH USER");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(btnUEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUView)
                .addGap(17, 17, 17))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUSearch)
                    .addComponent(txtUSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUView)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUEdit)
                        .addComponent(btnUDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jTabbedPane2.addTab("Users", jPanel9);

        jPanel2.setBackground(new java.awt.Color(119, 10, 10));

        tblRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERNAME", "MOVIE TITLE", "SHOW TIME (DATE & TIME)", "TICKET QTY", "TOTAL REVENUE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblRTable);

        btnRSearch.setText("SEARCH");
        btnRSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSearchActionPerformed(evt);
            }
        });

        btnRView.setText("VIEW ALL");
        btnRView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRViewActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(119, 10, 10));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 177, 164)));

        txtRGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRGenreActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("MOVIE TITLE");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SHOW TIME");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TICKET QTY");

        btnRClear.setText("CLEAR");
        btnRClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRClearActionPerformed(evt);
            }
        });

        btnRAdd.setText("ADD RECORD");
        btnRAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAddActionPerformed(evt);
            }
        });

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("USERNAME");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtRFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txtRQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnRClear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRAdd)
                    .addComponent(btnRClear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        btnRDelete.setText("DELETE RECORD");
        btnRDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRDeleteActionPerformed(evt);
            }
        });

        btnREdit.setText("EDIT RECORD");
        btnREdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREditActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SEARCH FILM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRView)
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnREdit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRDelete))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRSearch)
                    .addComponent(btnRView)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnREdit)
                        .addComponent(btnRDelete))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jTabbedPane2.addTab("Summaries / Reports", jPanel2);

        jPanel8.setBackground(new java.awt.Color(119, 10, 10));

        btnMDelete.setText("DELETE RECORD");
        btnMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMDeleteActionPerformed(evt);
            }
        });

        btnMEdit.setText("EDIT RECORD");
        btnMEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMEditActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(119, 10, 10));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 177, 164)));

        cmbMCinema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cineplex1", "Cineplex2", "Cineplex3", "Cineplex4", "Cineplex5" }));
        cmbMCinema.setSelectedIndex(-1);
        cmbMCinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMCinemaActionPerformed(evt);
            }
        });

        cmbMGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action", "Adventure", "Comedy", "Drama", "Fantasy", "Horror", "LGBTQ+", "Mystery", "Romance", "Science fiction" }));
        cmbMGenre.setSelectedIndex(-1);
        cmbMGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMGenreActionPerformed(evt);
            }
        });

        txtMDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMDateActionPerformed(evt);
            }
        });

        cmbMStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Now Showing", "Coming Soon" }));
        cmbMStatus.setSelectedIndex(-1);
        cmbMStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMStatusActionPerformed(evt);
            }
        });

        cmbMTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM", "6:00 PM", "8:00 PM" }));
        cmbMTime.setSelectedIndex(-1);
        cmbMTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMTimeActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FILM");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CINEMA");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SCREEN");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DATE");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TIME");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("STATUS");

        btnMClear.setText("CLEAR");
        btnMClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMClearActionPerformed(evt);
            }
        });

        btnMAdd.setText("ADD RECORD");
        btnMAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAddActionPerformed(evt);
            }
        });

        cmbMScreen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cmbMScreen.setSelectedIndex(-1);
        cmbMScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMScreenActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("GENRE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbMStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMClear, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtMFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbMCinema, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMDate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(cmbMTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMCinema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMClear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMAdd)
                    .addComponent(cmbMStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        btnMSearch.setText("SEARCH");
        btnMSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMSearchActionPerformed(evt);
            }
        });

        btnMView.setText("VIEW ALL");
        btnMView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMViewActionPerformed(evt);
            }
        });

        tblMTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FILM", "GENRE", "CINEMA", "SCREEN", "RELEASE DATE", "TIME", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMTable);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("SEARCH FILM");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMView)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnMEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMSearch)
                    .addComponent(btnMView)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMDelete)
                        .addComponent(btnMEdit))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jTabbedPane2.addTab("Movie Management", jPanel8);

        jButton1.setBackground(new java.awt.Color(119, 10, 10));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG OUT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(119, 10, 10));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMDateActionPerformed

    private void cmbMStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMStatusActionPerformed

    private void btnMClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMClearActionPerformed
        // TODO add your handling code here:
            txtMFilm.setText("");
            cmbMGenre.setSelectedIndex(-1);
            cmbMCinema.setSelectedIndex(-1);
            cmbMScreen.setSelectedIndex(-1);
            txtMDate.setText("");
            cmbMTime.setSelectedIndex(-1);
            cmbMStatus.setSelectedIndex(-1);
    }//GEN-LAST:event_btnMClearActionPerformed

    private void cmbMCinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMCinemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMCinemaActionPerformed

    private void btnMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMDeleteActionPerformed
        // TODO add your handling code here:
          int confirm = JOptionPane.showConfirmDialog(null,"Do you want to delete this record?","Delete Record",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
        DefaultTableModel model = (DefaultTableModel)tblMTable.getModel();
        int selectedRecord = tblMTable.getSelectedRow();
        
        model.removeRow(selectedRecord);
        JOptionPane.showMessageDialog(null, "DELETE SUCCESSFULLY!", "RECORD DELETE", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "DELETE NOT SUCCESSFUL", "RECORD DELETE", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMDeleteActionPerformed

    private void btnMEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblMTable.getModel();
        int row = tblMTable.getSelectedRow();
     
        model.setValueAt(txtMFilm.getText(), row, 0);
        model.setValueAt(cmbMGenre.getSelectedItem(), row, 1);
        model.setValueAt(cmbMCinema.getSelectedItem(), row, 2);
        model.setValueAt(cmbMScreen.getSelectedItem(), row, 3);
        model.setValueAt(txtMDate.getText(), row, 4);  
        model.setValueAt(cmbMTime.getSelectedItem(), row, 5);
        model.setValueAt(cmbMStatus.getSelectedItem(), row, 6);
    }//GEN-LAST:event_btnMEditActionPerformed

    private void btnUEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUEditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
        int row = tblUsers.getSelectedRow();
        
        model.setValueAt(txtUsername.getText(), row, 0);
        model.setValueAt(cmbRole.getSelectedItem(), row, 1);
        model.setValueAt(txtPass.getText(), row, 2);

    }//GEN-LAST:event_btnUEditActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void btnMAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblMTable.getModel();
        
      
        model.addRow(new Object[]{
            
            txtMFilm.getText(),
            cmbMGenre.getSelectedItem(),
            cmbMCinema.getSelectedItem(),
            cmbMScreen.getSelectedItem(),
            txtMDate.getText(),
            cmbMTime.getSelectedItem(),
            cmbMStatus.getSelectedItem()
        }
        );
    }//GEN-LAST:event_btnMAddActionPerformed

    private void cmbMGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMGenreActionPerformed

    private void btnUClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUClearActionPerformed
        // TODO add your handling code here:
        txtUsername.setText("");
        cmbRole.setSelectedIndex(-1);
        txtPass.setText("");
    }//GEN-LAST:event_btnUClearActionPerformed

    private void btnUAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
        
      
        model.addRow(new Object[]{
            txtUsername.getText(),
            cmbRole.getSelectedItem(),
            txtPass.getText()
        }
        );
    }//GEN-LAST:event_btnUAddActionPerformed

    private void btnUDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUDeleteActionPerformed
        // TODO add your handling code here:
          int confirm = JOptionPane.showConfirmDialog(null,"Do you want to delete this record?","Delete Record",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
        DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
        int selectedRecord = tblUsers.getSelectedRow();
        
        model.removeRow(selectedRecord);
        JOptionPane.showMessageDialog(null, "DELETE SUCCESSFULLY!", "RECORD DELETE", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "DELETE NOT SUCCESSFUL", "RECORD DELETE", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnUDeleteActionPerformed

    private void btnUSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
         TableRowSorter<DefaultTableModel>aaa=new TableRowSorter<>(model);
         tblUsers.setRowSorter(aaa);
         aaa.setRowFilter(RowFilter.regexFilter(txtUSearch.getText()));
    }//GEN-LAST:event_btnUSearchActionPerformed

    private void btnUViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUViewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
         TableRowSorter<DefaultTableModel>aaa=new TableRowSorter<>(model);
         tblUsers.setRowSorter(aaa);
         aaa.setRowFilter(RowFilter.regexFilter(""));
    }//GEN-LAST:event_btnUViewActionPerformed

    private void cmbMScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMScreenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMScreenActionPerformed

    private void cmbMTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMTimeActionPerformed

    private void txtRGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRGenreActionPerformed

    private void btnRClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRClearActionPerformed
        // TODO add your handling code here:
        txtRGenre.setText("");
        txtRFilm.setText("");
        txtRShowTime.setText("");
        txtRQTY.setText("");
    }//GEN-LAST:event_btnRClearActionPerformed

    private void btnRAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblRTable.getModel();
        float qty = Float.parseFloat(txtRQTY.getText());
        float rev = qty*350;
        
        
      
        model.addRow(new Object[]{
            txtRGenre.getText(),
            txtRFilm.getText(),
            txtRShowTime.getText(),
            txtRQTY.getText(),  
            rev
        }
               
        );
    }//GEN-LAST:event_btnRAddActionPerformed

    private void btnMSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblMTable.getModel();
         TableRowSorter<DefaultTableModel>aaa=new TableRowSorter<>(model);
         tblMTable.setRowSorter(aaa);
         aaa.setRowFilter(RowFilter.regexFilter(txtMSearch.getText()));
    }//GEN-LAST:event_btnMSearchActionPerformed

    private void btnMViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMViewActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tblMTable.getModel();
         TableRowSorter<DefaultTableModel>aaa=new TableRowSorter<>(model);
         tblMTable.setRowSorter(aaa);
         aaa.setRowFilter(RowFilter.regexFilter(""));
    }//GEN-LAST:event_btnMViewActionPerformed

    private void btnRSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSearchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblRTable.getModel();
         TableRowSorter<DefaultTableModel>aaa=new TableRowSorter<>(model);
         tblRTable.setRowSorter(aaa);
         aaa.setRowFilter(RowFilter.regexFilter(txtRSearch.getText()));
    }//GEN-LAST:event_btnRSearchActionPerformed

    private void btnRViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRViewActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tblRTable.getModel();
         TableRowSorter<DefaultTableModel>aaa=new TableRowSorter<>(model);
         tblRTable.setRowSorter(aaa);
         aaa.setRowFilter(RowFilter.regexFilter(""));
    }//GEN-LAST:event_btnRViewActionPerformed

    private void tblMTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblMTable.getModel();
        int row = tblMTable.getSelectedRow();
        
        txtMFilm.setText(model.getValueAt(row,0).toString());
        String genre1 = model.getValueAt(row, 1).toString();
        switch (genre1) {
            case "Action":
                cmbMGenre.setSelectedIndex(0);
                break;
            case "Adventure":
                cmbMGenre.setSelectedIndex(1);
                break;
            case "Comedy":
                cmbMGenre.setSelectedIndex(2);
                break;
            case "Drama":
                cmbMGenre.setSelectedIndex(3);
                break;   
            case "Fantasy":
                cmbMGenre.setSelectedIndex(4);
                break;
            case "Horror":
                cmbMGenre.setSelectedIndex(5);
                break;
            case "LGBTQ+":
                cmbMGenre.setSelectedIndex(6);
                break;
            case "Mystery":
                cmbMGenre.setSelectedIndex(7);
                break;
            case "Romance":
                cmbMGenre.setSelectedIndex(8);
                break;
            case "Science Fiction":
                cmbMGenre.setSelectedIndex(9);
                break;
        }
        
        String cin = model.getValueAt(row, 2).toString();
        switch (cin) {
            case "Cineplex1":
                cmbMCinema.setSelectedIndex(0);
                break;
            case "Cineplex2":
                cmbMCinema.setSelectedIndex(1);
                break;
            case "Cineplex3":
                cmbMCinema.setSelectedIndex(2);
                break;
            case "Cineplex4":
                cmbMCinema.setSelectedIndex(3);
                break;   
            case "Cineplex5":
                cmbMCinema.setSelectedIndex(4);
                break;
        }
        
        String scr = model.getValueAt(row, 3).toString();
        switch (scr) {
            case "1":
                cmbMScreen.setSelectedIndex(0);
                break;
            case "2":
                cmbMScreen.setSelectedIndex(1);
                break;
            case "3":
                cmbMScreen.setSelectedIndex(2);
                break;
            case "4":
                cmbMScreen.setSelectedIndex(3);
                break;   
            case "5":
                cmbMScreen.setSelectedIndex(4);
                break;
        }
        
        txtMDate.setText(model.getValueAt(row,4).toString());
        String tim = model.getValueAt(row, 5).toString();
        switch (tim) {
            case "10:00 AM":
                cmbMTime.setSelectedIndex(0);
                break;
            case "12:00 PM":
                cmbMTime.setSelectedIndex(1);
                break;
            case "2:00 PM":
                cmbMTime.setSelectedIndex(2);
                break;
            case "4:00 PM":
                cmbMTime.setSelectedIndex(3);
                break;   
            case "6:00 PM":
                cmbMTime.setSelectedIndex(4);
                break;
            case "8:00 PM":
                cmbMTime.setSelectedIndex(4);
                break;
              
        }
        String stat = model.getValueAt(row, 6).toString();
        switch (stat) {
            case "Now Showing":
                cmbMStatus.setSelectedIndex(0);
                break;
            case "Coming Soon":
                cmbMStatus.setSelectedIndex(1);
                break;
        }
        
    }//GEN-LAST:event_tblMTableMouseClicked

    private void tblUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsersMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
        int row = tblUsers.getSelectedRow();
        
        txtUsername.setText(model.getValueAt(row,0).toString());
        
        String role = model.getValueAt(row, 1).toString();
        switch (role) {
            case "ADMIN":
                cmbRole.setSelectedIndex(0);
                break;
            case "CUSTOMER":
                cmbRole.setSelectedIndex(1);
                break;
            case "VIP":
                cmbRole.setSelectedIndex(2);
                break; 
        }
        txtPass.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblUsersMouseClicked

    private void tblRTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tblRTable.getModel();
        int row = tblRTable.getSelectedRow();
        
        txtRGenre.setText(model.getValueAt(row,0).toString());
        txtRFilm.setText(model.getValueAt(row,1).toString());
        txtRShowTime.setText(model.getValueAt(row,2).toString());
        txtRQTY.setText(model.getValueAt(row,3).toString());
            
        
    }//GEN-LAST:event_tblRTableMouseClicked

    private void btnRDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRDeleteActionPerformed
        // TODO add your handling code here:
            int confirm = JOptionPane.showConfirmDialog(null,"Do you want to delete this record?","Delete Record",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirm == JOptionPane.YES_OPTION){
        DefaultTableModel model = (DefaultTableModel)tblRTable.getModel();
        int selectedRecord = tblRTable.getSelectedRow();
        
        model.removeRow(selectedRecord);
        JOptionPane.showMessageDialog(null, "DELETE SUCCESSFULLY!", "RECORD DELETE", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "DELETE NOT SUCCESSFUL", "RECORD DELETE", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRDeleteActionPerformed

    private void btnREditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREditActionPerformed
        // TODO add your handling code here:
 DefaultTableModel model = (DefaultTableModel)tblRTable.getModel();
        int row = tblRTable.getSelectedRow();
        
        model.setValueAt(txtRFilm.getText(), row, 0);
        model.setValueAt(txtRGenre.getText(), row, 1);
        model.setValueAt(txtRShowTime.getText(), row, 2);
        model.setValueAt(txtRQTY.getText(), row, 3);
    }//GEN-LAST:event_btnREditActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        adminMainMenu uClass = new adminMainMenu("admin");
        uClass.setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this,"Are you sure you want log off?","LOG OFF?", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if (response == JOptionPane.YES_OPTION){
       
           Main h = new Main();
           h.setVisible(true);
           this.setVisible(false);}
       else {
       this.setVisible(true);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMClear;
    private javax.swing.JButton btnMDelete;
    private javax.swing.JButton btnMEdit;
    private javax.swing.JButton btnMSearch;
    private javax.swing.JButton btnMView;
    private javax.swing.JButton btnRAdd;
    private javax.swing.JButton btnRClear;
    private javax.swing.JButton btnRDelete;
    private javax.swing.JButton btnREdit;
    private javax.swing.JButton btnRSearch;
    private javax.swing.JButton btnRView;
    private javax.swing.JButton btnUAdd;
    private javax.swing.JButton btnUClear;
    private javax.swing.JButton btnUDelete;
    private javax.swing.JButton btnUEdit;
    private javax.swing.JButton btnUSearch;
    private javax.swing.JButton btnUView;
    private javax.swing.JComboBox<String> cmbMCinema;
    private javax.swing.JComboBox<String> cmbMGenre;
    private javax.swing.JComboBox<String> cmbMScreen;
    private javax.swing.JComboBox<String> cmbMStatus;
    private javax.swing.JComboBox<String> cmbMTime;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tblMTable;
    private javax.swing.JTable tblRTable;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtMDate;
    private javax.swing.JTextField txtMFilm;
    private javax.swing.JTextField txtMSearch;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtRFilm;
    private javax.swing.JTextField txtRGenre;
    private javax.swing.JTextField txtRQTY;
    private javax.swing.JTextField txtRSearch;
    private javax.swing.JTextField txtRShowTime;
    private javax.swing.JTextField txtUSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
